### ISSUE TITLE
Cannot flash the twrp following the instructions in the site

### ISSUE THREAD

**Issue by MarcAnt01** [TeamWin/android_device_xiaomi_jasmine_sprout#2]
![image](https://user-images.githubusercontent.com/43090263/59423808-2af7a780-8dd3-11e9-8aeb-9a1ec3724cdb.png)

**Comment by bigbiff** [comment]
You need to use the correct path. The instructions are a placeholder. Closing because this isn't a TWRP issue.

**Comment by MarcAnt01** [comment]
@bigbiff it is in the right folder, check the screenshot

**Comment by bigbiff** [comment]
The path is not path/to/twrp. It's in your adb directory in platform-tools. Take out the path, you are in the directory anyway.

**Comment by MarcAnt01** [comment]
I have to create a folder path/to/twrp and enter the command in platform-tools folder, right?

**Comment by bigbiff** [comment]
I see your image in platform-tools. Why not just try fastboot boot twrp.img? I assume you renamed it from the twrp.me site?

**Comment by MarcAnt01** [comment]
I have changed the image name to twrp.imgand the installer name to twrp.zip to make it easier to do write in prompt. Following a guide on the web with simple boot twrp.img, it worked, I have flashed the twrp installer via adb, but when rebooting to recovery it is stuck to splash screen

**Comment by gilcu3** [comment]
> I have changed the image name to twrp.imgand the installer name to twrp.zip to make it easier to do write in prompt. Following a guide on the web with simple boot twrp.img, it worked, I have flashed the twrp installer via adb, but when rebooting to recovery it is stuck to splash screen

The same happens to me, even with last version 3.3.1, is it normal behaviour? Or there is a way to flash twrp permanently?
