### ISSUE TITLE
Why advicing Xiaomi tool to unlock bootloader?

### ISSUE THREAD

**Issue by MarcAnt01** [TeamWin/android_device_xiaomi_jasmine_sprout#3]
With Xiaomi Mi A2 it's enough to use fastboot oem unlock, I think it should be added in the info about the device in twrp.me, as it's an easier solution

**Comment by bigbiff** [comment]
Hi, feel free to submit updates to the markdown in the twrpme project at https://gerrit.twrp.me

This isn't really a bug for the device, so I am closing the issue.

**Comment by MarcAnt01** [comment]
> Hi, feel free to submit updates to the markdown in the twrpme project at https://gerrit.twrp.me
> This isn't really a bug for the device, so I am closing the issue.

Thanks, just looking for the best place where to report that
